version: "3"
networks:
    bullfighters-net:
        driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: bullfighters-mysql
    tty: true
    ports:
        - "4208:3306"
    volumes:
        - "/var/libclea/mysql/:/var/lib/mysql"
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: bullfighters
        MYSQL_USER: loken
        MYSQL_PASSWORD: 1234
    networks:
        - bullfighters-net
        
  server:
      image: wordpress:latest
      container_name: bullfighters-wordpress
      ports:
          - "4282:80"
      volumes:
          - /var/www/html/:/var/www/html
      environment:
          WORDPRESS_DB_USER: loken
          WORDPRESS_DB_PASSWORD: 1234
          WORDPRESS_DB_NAME: bullfighters
          WORDPRESS_DB_HOST: bullfighters-mysql
      depends_on:
          - mysql
      networks:
          - bullfighters-net

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: bullfighters-phpmyadmin
      ports:
          - "4283:80"
      environment:
          PMA_HOST: bullfighters-mysql
          MYSQL_ROOT_PASSWORD: 1234
      depends_on:
          - mysql
      networks:
          - bullfighters-net